### ISSUE TITLE
关于embedding.npy文件获取问题

### ISSUE THREAD

**Issue by YMCVICTOR** [lovemefan/SenseVoice-python#5]
您好，我看到您在huggingface上开源的模型中有embedding.npy文件，这个文件是如何计算出来的呢？

**Comment by lovemefan** [comment]
你好，这个embedding是官方模型中提取出来的，是模型中的一部分，参数是训练得到的

**Comment by YMCVICTOR** [comment]
感谢您的回答，具体怎么提取的您方便说吗，目前没找到怎么通过FunASR官方提取出来这个，然后我还尝试把您在huggingface开源的.onnx文件替换为使用FunASR导出SenseVoiceSmall的onnx模型，报错了(只更换了SenseVoiceSmall的onnx模型文件)。所以还想问下您导出onnx模型时在官方的代码基础上做什么改动了吗？
![Snipaste_2024-09-24_14-34-55](https://github.com/user-attachments/assets/da236f63-28b4-42ee-b754-acf185cd2ea0)

**Comment by lovemefan** [comment]
感谢关注和提问，这个项目中的onnx导出代码没有采用官方的onnx导出。这里的embedding对应pytorch中embed.weight。这里的onnx的计算图只包括encoder和decoder的forward，输入为concat(language_query, event_emo_query, textnorm_query, speech)。和官方的onnx输入输出应该有差异

**Comment by YMCVICTOR** [comment]
好嘞好嘞，我先按您说的去尝试一下，有问题再来问您，后面会考虑开源导出模型的部分吗

**Comment by YMCVICTOR** [comment]
您好，我尝试了一下，但是没有成功，具体的onnx模型的导出细节您方便给一下吗，就是图里的具体细节
![Snipaste_2024-09-25_16-46-00](https://github.com/user-attachments/assets/9396d421-aef1-4371-9a81-4bdca1a34bb2)

**Comment by lovemefan** [comment]
抱歉，忙忘了，近几天会给出导出细节，或者适配官方onnx也行

**Comment by YMCVICTOR** [comment]
好呢好呢，感谢回复，前几天我又尝试了一下，然后根据您开源的模型推出来了导出代码

**Comment by ILG2021** [comment]
能贴下转换代码吗？谢谢

**Comment by ILG2021** [comment]
@lovemefan @YMCVICTOR
